### ISSUE TITLE
Support for ME2 - Legendary edition

### ISSUE THREAD

**Issue by JPVenson** [gibbed/Gibbed.MassEffect2#1]
Hey,

Are you planning on support for the Legendary edition?

**Comment by gibbed** [comment]
Yeah, when I have time / pick up the Legendary edition. Haven't gotten to it yet.

**Comment by SLenik** [comment]
@gibbed see https://github.com/gibbed/Gibbed.MassEffect2/pull/3

**Comment by gibbed** [comment]
Resolved with 5b70ecd.
